# Dockerfile for trojan based alpine
# Copyright (C) 2020 Teddysun <i@teddysun.com>
# Reference URL:
# https://github.com/trojan-gfw/trojan
# https://trojan-gfw.github.io/trojan/

FROM alpine:latest
#WORKDIR /root
#RUN set -ex \
#	&& apk add --no-cache git build-base cmake boost-dev openssl-dev mariadb-connector-c-dev \
#	&& git clone https://github.com/trojan-gfw/trojan.git \
#	&& cd trojan \
#	&& cmake . \
#	&& make \
#	&& strip -s trojan

RUN set -ex \
	&& apk add --no-cache tzdata ca-certificates libstdc++ boost-system boost-program_options mariadb-connector-c

COPY trojan /usr/bin/trojan
COPY server.conf /etc/trojan/server.conf
COPY cert/server.key /etc/trojan/server.key
COPY cert/server.crt /etc/trojan/server.crt
CMD [ "/usr/bin/trojan", "-c", "/etc/trojan/server.conf" ]
